config/routes.rb
Spree::Core::Engine.routes.append do  
  namespace :admin do
    resources :reports, :only => [:index, :show] do  # <= add this block
      collection do
        get :product_sales
        post :product_sales
      end
    end
  end
end

app/controllers/spree/admin/reports_controller_decorator.rb
# add the sales tax report
Spree::Admin::ReportsController.add_available_report!(:product_sales, 'Product Sales Report')


Spree::Admin::ReportsController.class_eval do 
  before_action :product_sales_params, only: [:product_sales]

  def product_sales
    @search = Spree::Order.complete.ransack(params[:q])

    @orders = @search.result 

    line_items = @orders.map(&:line_items).flatten
    @products = line_items.map(&:product).group_by(&:id)
  end

  private
  def product_sales_params
    params[:q] = {} unless params[:q]

    if params[:q][:completed_at_gt].blank?
      params[:q][:completed_at_gt] = Time.zone.now.beginning_of_month
    else
      params[:q][:completed_at_gt] = Time.zone.parse(params[:q][:completed_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
    end

    if params[:q] && !params[:q][:completed_at_lt].blank?
      params[:q][:completed_at_lt] = Time.zone.parse(params[:q][:completed_at_lt]).end_of_day rescue ""
    else
      params[:q][:completed_at_lt] = Time.now.end_of_month
    end

    params[:q][:s] ||= "completed_at desc"
  end

end

app/views/spree/admin/reports/_report_order_criteria.slim
= search_form_for @search, :url => spree.product_sales_admin_reports_path  do |s|
  .date-range-filter.field.align-center
    = label_tag nil, Spree.t(:start), class: 'inline'
    = s.text_field :completed_at_gt, class: 'datepicker datepicker-from', value: datepicker_field_value(params[:q][:completed_at_gt])
    
    span.range-divider
      i.fa.fa-arrow-right        

    = s.text_field :completed_at_lt, class: 'datepicker datepicker-to', value: datepicker_field_value(params[:q][:completed_at_lt])
    = label_tag nil, Spree.t(:end), class: 'inline'

    .actions.filter-actions
      = button Spree.t(:search), 'search'

app/views/spree/admin/reports/product_sales.slim
- content_for :page_title do 
  = 'Product Sales Report'

- content_for :page_actions do
  li = link_to_with_icon 'arrow-left', 'Back To Reports List', spree.admin_reports_url, class: 'button'

- content_for :table_filter_title do
  = Spree.t(:date_range)

- content_for :table_filter do 
  = render :partial => 'report_order_criteria', :locals => {}

table.admin-report data-hook="sales_tax"
  thead
    tr
      th Product
      th Sold
  tbody
    - @products.each do |k,v|
      tr
        td = link_to v.first.name, admin_product_path(k)
        td = v.count      